config/routes.rb
Rails.application.routes.draw do

  resources :zonas do
    get "delete"
  end

  resources :animals do
    get "delete"
  end

root to: 'animals#index'

  devise_for :users
  # resources :animals

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :zona
  belongs_to :cuidador, class_name: 'User'

  def self.search(term)
    if term
      where('nom LIKE ?', "%#{term}%")
    else
      all
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :animals

  # validates :email, presence: true

end

app/models/zona.rb
class Zona < ApplicationRecord
  has_many :animals

  validates :temperatura, inclusion: { in: -20..60 }
    validates :humitat, inclusion: { in: 10..100 }
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.search(params[:term])
    #  @tasks = Task.search(params[:term])
    # @my_input = params['my_input']
  end

  def buscador
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @cuidadors = User.all()
    @zonas = Zona.all()
    @animal = Animal.new
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)
    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
      @cuidadors = User.all()
      @zonas = Zona.all()
  end

  def update
    @animals = Animal.all
    @animal.update_attributes(animal_params)
  end

  def delete
   @animal = Animal.find(params[:animal_id])
  end

  def destroy
    @animals = Animal.all
    @animal.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:nom, :raza, :zona_id, :any_naixement, :cuidador_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
end

app/controllers/zonas_controller.rb
class ZonasController < ApplicationController
  before_action :set_zona, only: [:show, :edit, :update, :destroy]

  # GET /zonas
  # GET /zonas.json
  def index
    @zonas = Zona.all
  end

  # GET /zonas/1
  # GET /zonas/1.json
  def show
  end

  # GET /zonas/new
  def new
    @zona = Zona.new
  end

  # GET /zonas/1/edit
  def edit

  end

  # POST /zonas
  # POST /zonas.json
  def create
  @zonas = Zona.all
  @zona = Zona.create(zona_params)
  end

  # PATCH/PUT /zonas/1
  # PATCH/PUT /zonas/1.json
  def update
    @zonas = Zona.all
    @zona.update_attributes(zona_params)
  end

  def delete
    @zona = Zona.find(params[:zona_id])
  end

  def destroy
    @zonas = Zona.all
    @zona.destroy
  end

  # DELETE /zonas/1
  # DELETE /zonas/1.json

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zona
      @zona = Zona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zona_params
      params.require(:zona).permit(:nom, :clima, :temperatura, :humitat)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zonas_helper.rb
module ZonasHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/animals/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete Animal</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete <b><%= @animal.nom %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Yes, Delete This Animal", animal_path(@animal), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/animals/_edit.html.erb
<div class="modal-header">
  <h3><%= "Editing #{@animal.nom}" %></h3>
</div>
<%= render "formAyax" %>

app/views/animals/_form.html.erb
<%= form_with(model: animal, local: true) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nom %>
    <%= form.text_field :nom, id: :animal_nom %>
  </div>

  <div class="field">
    <%= form.label :raza %>
    <%= form.text_field :raza, id: :animal_raza %>
  </div>

  <div class="field">
    <%= form.label :any_naixement %>
    <%= form.number_field :any_naixement, id: :animal_any_naixement %>
  </div>

  <div class="field">
  <%= form.label :cuidador_id %>
<%= form.select :cuidador_id, @cuidadors.collect { |cuidador| [cuidador.email, cuidador.id]} %>
</div>

  <div class="field">
  <%= form.label :zona_id %>
<%= form.select :zona_id, @zonas.collect { |zona| [zona.nom, zona.id]} %>
</div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/_formAyax.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for @animal, remote: true, html: { style: "display:inline;" } do |f| %>
      <div class="modal-body">
        <ul class="errors"></ul>

        <div class="form-group">
          <%= f.label :nom, class:"control-label" %>
          <%= f.text_field :nom, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :raza, class: "control-label" %>
          <%= f.text_field :raza, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :any_naixement, class: "control-label" %>
          <%= f.number_field :any_naixement, class: "form-control" %>
        </div>

        <div class="field">
        <%= f.label :zona_id %>
      <%= f.select :zona_id, @zonas.collect { |zona| [zona.nom, zona.id]} %>
      </div>

        <div class="form-group">
         <%= f.label :cuidador_id, class: "control-label" %>
         <%= f.select :cuidador_id, @cuidadors.collect { |cuidador| [cuidador.email, cuidador.id]}, class: "form-control" %>
        </div>


      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/animals/_index.html.erb
<% @animals.each do |animal| %>
  <tr>
    <td><%= animal.nom %></td>
      <td><%= animal.raza %></td>
        <td><%= animal.zona.nom %></td>
          <td><%= animal.any_naixement %></td>
          <td><%= animal.cuidador.email %></td>
    <td><%= link_to "Edit", edit_animal_path(animal), remote: true, class: "btn btn-default" %></td>
    <td><%= link_to "Delete", animal_delete_path(animal), remote: true, class: "btn btn-danger" %></td>
  </tr>
<% end %>

app/views/animals/_save.js.erb
$("ul.errors").html("")
<% if @animal.errors.any? %>
  <% @animal.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".animal-index").html("<%= escape_javascript(render 'index') %>")
  $("#animal-modal").modal("hide")
<% end %>

app/views/animals/create.js.erb
<%= render "save" %>

app/views/animals/delete.js.erb
$("#animal-modal").html("<%= escape_javascript(render 'delete') %>")
$("#animal-modal").modal("show")

app/views/animals/destroy.js.erb
<%= render "save" %>

app/views/animals/edit.js.erb
$("#animal-modal").html("<%= escape_javascript(render 'edit') %>")
$("#animal-modal").modal("show")

app/views/animals/index.html.erb
<div class="container">
  <div class="well">
    <%= link_to "New Animal", new_animal_path, class: "btn btn-primary" %>
  </div>
  <div class="new-animal"></div>

  <p>Buscador Animals</p>
  <%= form_tag(animals_path, method: :get, remote: true) do %>
    <%= text_field_tag :term, params[:term] %>
    <%= submit_tag 'Search', name: nil %>
  <% end %>


  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Nom</th>
        <th>Raza</th>
        <th>Zona</th>
        <th>Any naixement</th>
        <th>Cuidador</th>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </thead>
    <tbody class="animal-index">
    <p id="valueFiltre"></p>

      <%= render "index" %>
    </tbody>
  </table>
</div>
<div id="animal-modal" class="modal fade"></div>

app/views/animals/index.js.erb
$(".animal-index").html("<%= escape_javascript(render 'index') %>")

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @animal.nom %>
</p>

<p>
  <strong>Raza:</strong>
  <%= @animal.raza %>
</p>

<p>
  <strong>Zona:</strong>
  <%= @animal.zona.nom %>
</p>

<p>
  <strong>Any naixement:</strong>
  <%= @animal.any_naixement %>
</p>

<p>
  <strong>Cuidador:</strong>
  <%= @animal.cuidador.email %>
</p>

<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>

app/views/animals/update.js.erb
<%= render "save" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "M07Uf4Practica" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>



    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">M07Uf4Practica</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Animals", "/animals"  %></li>
            <li><%= link_to "Zonas", "/zonas"  %></li>
      <% if user_signed_in? %>
         <%= current_user.email %>.
              <li class=""><%= link_to 'Sign out', destroy_user_session_path,  :method => :delete %></li>
      <% else %>
            <li><%= link_to 'Register', new_user_registration_path %> </li>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
      <% end %>
            </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/zonas/_edit.html.erb
<div class="modal-header">
  <h3><%= "Editing #{@zona.nom}" %></h3>
</div>
<%= render "form" %>

app/views/zonas/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for @zona, remote: true, html: { style: "display:inline;" } do |f| %>
      <div class="modal-body">
        <ul class="errors"></ul>

        <div class="form-group">
          <%= f.label :nom, class:"control-label" %>
          <%= f.text_field :nom, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :clima, class: "control-label" %>
          <%= f.text_field :clima, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :temperatura, class: "control-label" %>
          <%= f.text_field :temperatura, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :humitat, class: "control-label" %>
          <%= f.text_field :humitat, class: "form-control" %>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/zonas/_formNoVALID.html.erb
<%= form_with(model: zona, local: true) do |form| %>
  <% if zona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zona.errors.count, "error") %> prohibited this zona from being saved:</h2>

      <ul>
      <% zona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nom %>
    <%= form.text_field :nom, id: :zona_nom %>
  </div>

  <div class="field">
    <%= form.label :clima %>
    <%= form.text_field :clima, id: :zona_clima %>
  </div>

  <div class="field">
    <%= form.label :temperatura %>
    <%= form.number_field :temperatura, id: :zona_temperatura %>
  </div>

  <div class="field">
    <%= form.label :humitat %>
    <%= form.number_field :humitat, id: :zona_humitat %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/zonas/_index.html.erb
<% @zonas.each do |zona| %>
  <tr>
    <td><%= zona.nom %></td>
    <td><%= zona.clima %></td>
    <td><%= zona.temperatura %></td>
    <td><%= zona.humitat %></td>
    <td><%= link_to "Edit", edit_zona_path(zona), remote: true, class: "btn btn-default" %></td>
    <td><%= link_to "Delete", zona_delete_path(zona), remote: true, class: "btn btn-danger" %></td>
  </tr>
<% end %>

app/views/zonas/_new.html.erb
<div class="modal-header">
<h3>New Zona</h3>
</div>
<%= render "form" %>

app/views/zonas/_save.js.erb
$("ul.errors").html("")
<% if @zona.errors.any? %>
  <% @zona.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".zona-index").html("<%= escape_javascript(render 'index') %>")
  $("#zona-modal").modal("hide")
<% end %>

app/views/zonas/delete.js.erb
$("#zona-modal").html("<%= escape_javascript(render 'delete') %>")
$("#zona-modal").modal("show")

app/views/zonas/edit.html.erb
<h1>Editing Zona</h1>

<%= render 'form', zona: @zona %>

<%= link_to 'Show', @zona %> |
<%= link_to 'Back', zonas_path %>

app/views/zonas/edit.js.erb
$("#zona-modal").html("<%= escape_javascript(render 'edit') %>")
$("#zona-modal").modal("show")

app/views/zonas/index.html.erb
<div class="container">
  <div class="well">
    <%= link_to "New Zona", new_zona_path, remote: true, class: "btn btn-primary" %>
  </div>
  <div class="new-zona"></div>

  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Nom</th>
        <th>Clima</th>
        <th>Temperatura</th>
        <th>Humitat</th>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </thead>
    <tbody class="zona-index">
      <%= render "index" %>
    </tbody>
  </table>
</div>
<div id="zona-modal" class="modal fade"></div>

app/views/zonas/indexNovalid.html.erb
<p id="notice"><%= notice %></p>

<h1>Zonas</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Clima</th>
      <th>Temperatura</th>
      <th>Humitat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zonas.each do |zona| %>
      <tr>
        <td><%= zona.nom %></td>
        <td><%= zona.clima %></td>
        <td><%= zona.temperatura %></td>
        <td><%= zona.humitat %></td>
        <td><%= link_to 'Show', zona %></td>
        <td><%= link_to 'Edit', edit_zona_path(zona) %></td>
        <td><%= link_to 'Destroy', zona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zona', new_zona_path %>

app/views/zonas/new.html.erb
<h1>New Zona</h1>

<%= render 'form', zona: @zona %>

<%= link_to 'Back', zonas_path %>

app/views/zonas/new.js.erb
$("#zona-modal").html("<%= escape_javascript(render 'new') %>")
$("#zona-modal").modal("show")

app/views/zonas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @zona.nom %>
</p>

<p>
  <strong>Clima:</strong>
  <%= @zona.clima %>
</p>

<p>
  <strong>Temperatura:</strong>
  <%= @zona.temperatura %>
</p>

<p>
  <strong>Humitat:</strong>
  <%= @zona.humitat %>
</p>

<%= link_to 'Edit', edit_zona_path(@zona) %> |
<%= link_to 'Back', zonas_path %>